### ISSUE TITLE
nothing important

### ISSUE THREAD

**Issue by abobafett-dev** [AmZakirov/CarcassoneRL#1]
Cool idea

**Comment by AmZakirov** [comment]
Thanks! Btw github version is realy out of date:/

________________________________
От: abobafett-dev ***@***.***>
Отправлено: 2 мая 2024 г. 10:18:12
Кому: AmZakirov/CarcassoneRL
Копия: Subscribed
Тема: [AmZakirov/CarcassoneRL] nothing important (Issue #1)





ВНЕШНЯЯ ПОЧТА:
        Если вы не знаете отправителя – не открывайте вложений, не переходите по ссылкам, не пересылайте
конфиденциальную информацию и никогда не вводите свой корпоративный логин и пароль.




EXTERNAL EMAIL:
        If the sender is unknown, do not click on links/attachments.
Never give out confidential information, especially your corporate user ID or password.





Cool idea and presentation
